### PR TITLE
Certes 3.0.4 update

### PR DESCRIPTION
**Pull request by patolax**
- Updated certes lib to 3.0.4
- PreferredChain from LetsEncryptOptions
- Fix unit tests

### CODE REVIEW

**Comment by ffMathy** [comment]
Thanks! It should be out within the next hour or so.

**Comment by patolax** [comment]
@ffMathy I don't see this version in Nuget. When can I expect the next release? really appreciate it if you look into this. Thanks!

**Comment by ffMathy** [comment]
I think a NuGet key has expired. See FluffySpoon.Publishers actions.

I need to fix it, I just haven't had the time.

**Comment by patolax** [comment]
Please let me know if I can help, we are eagerly waiting to upgrade our production service upon the release of this new version.

**Comment by ffMathy** [comment]
It should be resolved now.

**Pull request merged**
